### PR TITLE
FIX: Make the activity cards have the same size 

### PR DESCRIPTION
**Pull request by Mamoanwar97**

### CODE REVIEW

**Comment by Es7evam** [comment]
This fix broke some of the images, they don't seem to be fitting to the card anymore (horizontally), probably due style changes. Can you fix that?

image

As soon as that's fixed I can approve the PR.

**Comment by Es7evam** [comment]
It seems like you already fixed the bug at the other PR, I'll check that later and if that's the case I'll merge both then

**Comment by Mamoanwar97** [comment]
Okay this was a fix i wanted all images to fit the same space, but okay i will do it for you i am out for couple of hours and will do it when i return

And ah please accept each pr separately because i need to finish the hacktoberfest quest :,D or at least merge one and mark the other as hacktoberfeast accepted

**Comment by Es7evam** [comment]
I'll merge both separately, no worries
Thanks for the help 😃

**Comment by Mamoanwar97** [comment]
Would you prefer it like this? 
1)
image
or this : 
2)
image

if you like the first one, then you can merge directly if you prefer the second one tell me and i will commit it, thank you for merging my prs ^^

**Comment by Es7evam** [comment]
Thanks, merging..
I'll take a look at the other PR tomorrow

**Pull request merged**
